🚀 Day 15 – Introduction to Pandas
📚 Study Notes
What is Pandas?

Pandas is one of the most popular Python libraries for Data Analysis.

It helps you:

✅ Store data in tables
✅ Clean data
✅ Analyze datasets
✅ Work with Excel and CSV files

Import Pandas:

import pandas as pd
Series

A Series is a one-dimensional data structure.

import pandas as pd

s = pd.Series([10, 20, 30, 40])

print(s)

Output:

0    10
1    20
2    30
3    40
dtype: int64
DataFrame

A DataFrame is a two-dimensional table (rows and columns).

import pandas as pd

data = {
    "Name": ["Dhruv", "Aman", "Riya"],
    "Age": [20, 21, 19]
}

df = pd.DataFrame(data)

print(df)

Output:

    Name  Age
0  Dhruv   20
1   Aman   21
2   Riya   19
Rows & Columns
print(df.shape)

Output:

(3, 2)

Meaning:

3 Rows
2 Columns
Shape

Returns total rows and columns.

print(df.shape)
Columns

Returns all column names.

print(df.columns)

Output:

Index(['Name', 'Age'], dtype='object')
Info()

Provides dataset information.

print(df.info())

Shows:

Number of rows
Column names
Data types
Memory usage
Describe()

Provides statistical summary.

print(df.describe())

Output includes:

Count
Mean
Min
Max
Standard Deviation

In [4]:
import pandas as pd

data = {"Name" : ["Dhruv" , "Riya" , "Aarush"],
        "Age" : [20,21,19]}
        # "Marks" : [94,89,90]}
df = pd.DataFrame(data)

print(df)

     Name  Age
0   Dhruv   20
1    Riya   21
2  Aarush   19

In [7]:
print("Shape : " , "\nNo. of Rows : ", df.shape[0] , "\nNo. of Columns : " , df.shape[1])

Shape :
No. of Rows :  3
No. of Columns :  2

In [8]:
print(df.columns)

Index(['Name', 'Age'], dtype='object')

In [9]:
print("Info : " , df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes
Info :  None

In [11]:
# Create a Series containing 5 numbers.

k = [1,2,3,4,5]

df = pd.Series(k)
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [13]:
# Create a DataFrame with Name and City columns.
d = {"Name" : ["Dhruv" , "Aarush" , "Riya"] ,
     "City" : ["Noida" , "Hapur" , "Meerut"]}

df = pd.DataFrame(d)
df

     Name    City
0   Dhruv   Noida
1  Aarush   Hapur
2    Riya  Meerut

In [14]:
# Print the shape of the DataFrame.
df.shape

(3, 2)

In [15]:
# Print all column names.
df.columns

Index(['Name', 'City'], dtype='object')

In [16]:
# Display information about the DataFrame using info().
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   City    3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

In [17]:
# Create a DataFrame with 5 students and their marks.
d = {"Name" : ["Dhruv" , "Aarush" , "Riya" , "Priya" , "Komal"] ,
     "Marks" : [ 94, 90 , 89 , 78 , 90]}
df = pd.DataFrame(d)
df

     Name  Marks
0   Dhruv     94
1  Aarush     90
2    Riya     89
3   Priya     78
4   Komal     90

In [18]:
# Print only the Marks column.
df["Marks"]

0    94
1    90
2    89
3    78
4    90
Name: Marks, dtype: int64

In [19]:
# Find the number of rows and columns.
df.shape

(5, 2)

In [20]:
# Use describe() on the marks dataset.
df.describe()

           Marks
count   5.000000
mean   88.200000
std     6.016644
min    78.000000
25%    89.000000
50%    90.000000
75%    90.000000
max    94.000000

In [22]:
# Add a new column named "Grade".
df["Grade"] = ["A+" , "A" , "A" , "C" , "A"]
df

     Name  Marks Grade
0   Dhruv     94    A+
1  Aarush     90     A
2    Riya     89     A
3   Priya     78     C
4   Komal     90     A

In [26]:
# Create a DataFrame for employee data.
employee = {"Name" : ["Dhruv" , "Aarush" , "Riya" , "Priya" , "Komal"] ,
     "Department" : [ "IT", "HR" , "IT" , "Sales" , "IT"],
           "Salary" : [60000 , 30000, 40000, 50000 , 45000]}

df = pd.DataFrame(employee)
df

     Name Department  Salary
0   Dhruv         IT   60000
1  Aarush         HR   30000
2    Riya         IT   40000
3   Priya      Sales   50000
4   Komal         IT   45000

In [27]:
# Print only employee names.
df["Name"]

0     Dhruv
1    Aarush
2      Riya
3     Priya
4     Komal
Name: Name, dtype: object

In [28]:
# Find the average salary using Pandas.
df["Salary"].mean()

np.float64(45000.0)

In [30]:
# Display statistical summary using describe().
df.describe()

             Salary
count      5.000000
mean   45000.000000
std    11180.339887
min    30000.000000
25%    40000.000000
50%    45000.000000
75%    50000.000000
max    60000.000000

In [33]:
# Create a DataFrame with at least 10 rows and explore shape, columns, info(), and describe().

employee = {"Name" : ["Dhruv" , "Aarush" , "Riya" , "Priya" , "Komal","Rahul" , "Neha" , "Sharman" , "Rishabh" , "Aniket"] ,
     "Department" : [ "IT", "HR" , "IT" , "Sales" , "IT" , "IT", "HR" , "IT" , "Sales" , "IT"],
           "Salary" : [60000 , 30000, 40000, 50000 , 45000 , 60000 , 30000, 40000, 50000 , 45000]}

df = pd.DataFrame(employee)
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

(10, 3)
Index(['Name', 'Department', 'Salary'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Department  10 non-null     object
 2   Salary      10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes
None
             Salary
count     10.000000
mean   45000.000000
std    10540.925534
min    30000.000000
25%    40000.000000
50%    45000.000000
75%    50000.000000
max    60000.000000

In [37]:
# Student Performance Analyzer

# Features:

# ✅ Create a DataFrame of students
# ✅ Display all data
# ✅ Show average marks
# ✅ Show highest marks
# ✅ Show lowest marks
# ✅ Print DataFrame shape

students = {
    "Name": ["Dhruv", "Aman", "Riya", "Priya", "Karan"],
    "Marks": [85, 90, 88, 92, 80]
}

df = pd.DataFrame(students)
print(df)
print("Avg : ",df["Marks"].mean())
print("Hightest  :",df["Marks"].max())
print("Lowest : ",df["Marks"].min())
print(df.shape)

    Name  Marks
0  Dhruv     85
1   Aman     90
2   Riya     88
3  Priya     92
4  Karan     80
Avg :  87.0
Hightest  : 92
Lowest :  80
(5, 2)