Day 17 – Selecting & Filtering Data (Pandas)
🎯 Today's Goal

By the end of today, you should be able to:

✅ Select single columns

✅ Select multiple columns

✅ Filter rows based on conditions

✅ Apply multiple conditions

✅ Find specific data from a dataset

📚 Study Notes
1️⃣ Selecting a Single Column
df["Sales"]

Example:

import pandas as pd

df = pd.read_csv("superstore.csv")

print(df["Sales"])
2️⃣ Selecting Multiple Columns
df[["Sales", "Profit"]]

Example:

print(df[["Sales", "Profit"]])
3️⃣ Filtering Data
Sales greater than 1000
df[df["Sales"] > 1000]

Example:

high_sales = df[df["Sales"] > 1000]

print(high_sales)
4️⃣ Multiple Conditions
Sales > 1000 AND Profit > 100
df[(df["Sales"] > 1000) & (df["Profit"] > 100)]

Example:

result = df[(df["Sales"] > 1000) & (df["Profit"] > 100)]

print(result)

In [ ]:
import pandas as pd

df = pd.read_csv("customer_dataset.csv")
df.head()

   CustomerID   Name   Age    City  PurchaseAmount
0         101   Aman  22.0   Delhi          1200.0
1         102   Riya  24.0  Mumbai          2500.0
2         103  Dhruv   NaN    Pune          1800.0
3         104  Priya  28.0   Delhi             NaN
4         105  Karan  30.0     NaN          3200.0

In [ ]:
# Display only the Name column.
df["Name"]

0      Aman
1      Riya
2     Dhruv
3     Priya
4     Karan
5      Neha
6     Arjun
7    Simran
8     Rohit
9    Anjali
Name: Name, dtype: object

In [ ]:
# Display only the City column.
df["City"]

0         Delhi
1        Mumbai
2          Pune
3         Delhi
4           NaN
5        Jaipur
6        Mumbai
7          Pune
8         Delhi
9    Chandigarh
Name: City, dtype: object

In [ ]:
# Display both Name and PurchaseAmount.
df[["Name" , "PurchaseAmount"]]

     Name  PurchaseAmount
0    Aman          1200.0
1    Riya          2500.0
2   Dhruv          1800.0
3   Priya             NaN
4   Karan          3200.0
5    Neha          2100.0
6   Arjun          1500.0
7  Simran          2700.0
8   Rohit             NaN
9  Anjali          1900.0

In [ ]:
# Find customers whose PurchaseAmount > 2000.
df[df["PurchaseAmount"] > 2000]

   CustomerID    Name   Age    City  PurchaseAmount
1         102    Riya  24.0  Mumbai          2500.0
4         105   Karan  30.0     NaN          3200.0
5         106    Neha  25.0  Jaipur          2100.0
7         108  Simran   NaN    Pune          2700.0

In [ ]:
# Find customers from Delhi.
df[df["City"] == "Delhi"]

   CustomerID   Name   Age   City  PurchaseAmount
0         101   Aman  22.0  Delhi          1200.0
3         104  Priya  28.0  Delhi             NaN
8         109  Rohit  31.0  Delhi             NaN

In [ ]:
# Find customers whose Age > 25.
df[df["Age"] > 20]

   CustomerID    Name   Age        City  PurchaseAmount
0         101    Aman  22.0       Delhi          1200.0
1         102    Riya  24.0      Mumbai          2500.0
3         104   Priya  28.0       Delhi             NaN
4         105   Karan  30.0         NaN          3200.0
5         106    Neha  25.0      Jaipur          2100.0
6         107   Arjun  27.0      Mumbai          1500.0
8         109   Rohit  31.0       Delhi             NaN
9         110  Anjali  23.0  Chandigarh          1900.0

In [ ]:
# Find customers from Delhi whose purchase amount is greater than 1000.
df[(df["City"] == "Delhi") & (df["PurchaseAmount"] > 1000)]

   CustomerID  Name   Age   City  PurchaseAmount
0         101  Aman  22.0  Delhi          1200.0

In [ ]:
# Find customers whose age is less than 30.
df[df["Age"] < 30]

   CustomerID    Name   Age        City  PurchaseAmount
0         101    Aman  22.0       Delhi          1200.0
1         102    Riya  24.0      Mumbai          2500.0
3         104   Priya  28.0       Delhi             NaN
5         106    Neha  25.0      Jaipur          2100.0
6         107   Arjun  27.0      Mumbai          1500.0
9         110  Anjali  23.0  Chandigarh          1900.0

In [ ]:
# Find customers whose purchase amount is between 1500 and 3000.
df[(df["PurchaseAmount"]<3000) & (df["PurchaseAmount"]>1500)]

   CustomerID    Name   Age        City  PurchaseAmount
1         102    Riya  24.0      Mumbai          2500.0
2         103   Dhruv   NaN        Pune          1800.0
5         106    Neha  25.0      Jaipur          2100.0
7         108  Simran   NaN        Pune          2700.0
9         110  Anjali  23.0  Chandigarh          1900.0

In [ ]:
# Find customers whose city is either Delhi or Mumbai.
df[(df["City"] == "Delhi") & (df["City"] == "Mumbai")]

Empty DataFrame
Columns: [CustomerID, Name, Age, City, PurchaseAmount]
Index: []

In [ ]:
# Find customers with missing values.
customer_with_missing = df[df.isnull().any(axis=1)]
customer_with_missing

   CustomerID    Name   Age   City  PurchaseAmount
2         103   Dhruv   NaN   Pune          1800.0
3         104   Priya  28.0  Delhi             NaN
4         105   Karan  30.0    NaN          3200.0
7         108  Simran   NaN   Pune          2700.0
8         109   Rohit  31.0  Delhi             NaN

In [ ]:
# Find customers whose age is missing.
df[df["Age"].isnull()]

   CustomerID    Name  Age  City  PurchaseAmount
2         103   Dhruv  NaN  Pune          1800.0
7         108  Simran  NaN  Pune          2700.0

In [ ]:
# Find the top 3 customers with the highest purchase amount.
top_3_customer = df.sort_values(by = "PurchaseAmount" , ascending = False).head(3)
top_3_customer

   CustomerID    Name   Age    City  PurchaseAmount
4         105   Karan  30.0     NaN          3200.0
7         108  Simran   NaN    Pune          2700.0
1         102    Riya  24.0  Mumbai          2500.0

In [ ]:
avg_purchase_amt = df["PurchaseAmount"].mean()
df[df["PurchaseAmount"] > avg_purchase_amt]

   CustomerID    Name   Age    City  PurchaseAmount
1         102    Riya  24.0  Mumbai          2500.0
4         105   Karan  30.0     NaN          3200.0
7         108  Simran   NaN    Pune          2700.0

In [ ]:
# Find the oldest customer.
k = df["Age"].max()
k
df[df["Age"] == k]

   CustomerID   Name   Age   City  PurchaseAmount
8         109  Rohit  31.0  Delhi             NaN

In [ ]:
# Find customers whose purchase amount is below 2000 and age is above 25.
df[(df["PurchaseAmount"] < 2000) & (df["Age"] > 25)]

   CustomerID   Name   Age    City  PurchaseAmount
6         107  Arjun  27.0  Mumbai          1500.0

In [4]:
import pandas as pd

df = pd.read_csv("sales_data.csv")

In [5]:
# Display only Sales_Amount.
df["Sales_Amount"]

0      5053.97
1      4384.02
2      4631.23
3      2167.94
4      3750.20
        ...
995    4733.88
996    4716.36
997    7629.70
998    1629.47
999    4923.93
Name: Sales_Amount, Length: 1000, dtype: float64

In [6]:
# Display Product_Category and Sales_Amount.
df[["Product_Category" , "Sales_Amount"]]

    Product_Category  Sales_Amount
0          Furniture       5053.97
1          Furniture       4384.02
2               Food       4631.23
3           Clothing       2167.94
4        Electronics       3750.20
..               ...           ...
995             Food       4733.88
996         Clothing       4716.36
997         Clothing       7629.70
998      Electronics       1629.47
999             Food       4923.93

[1000 rows x 2 columns]

In [7]:
# Find sales where Sales_Amount > 5000.
df[df["Sales_Amount"] > 5000]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
12,1024,2023-11-11,Eve,West,6607.80,21,Food,622.01,641.09,Returning,0.00,Bank Transfer,Retail,West-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,1074,2023-12-16,Bob,North,6310.56,19,Furniture,278.67,423.13,New,0.24,Credit Card,Online,North-Bob
983,1039,2023-08-01,Eve,West,7527.63,36,Clothing,2919.00,3125.01,New,0.24,Cash,Online,West-Eve
989,1025,2023-12-30,David,West,9215.32,28,Electronics,2097.84,2270.99,New,0.13,Credit Card,Retail,West-David
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David

In [8]:
# Find sales made in the North region.
df[df["Region"] == "North"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
15,1053,2023-10-16,Bob,North,2235.83,48,Furniture,121.19,487.65,New,0.18,Cash,Retail,North-Bob
16,1002,2023-05-30,David,North,6810.35,17,Furniture,4024.76,4420.15,Returning,0.04,Cash,Online,North-David
20,1002,2023-04-22,Eve,North,6551.23,9,Electronics,4398.16,4439.12,New,0.18,Bank Transfer,Online,North-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,1090,2023-01-04,Eve,North,1028.39,14,Furniture,4037.21,4323.71,Returning,0.27,Credit Card,Online,North-Eve
988,1044,2023-08-08,Alice,North,4912.69,18,Clothing,430.14,641.18,New,0.13,Cash,Online,North-Alice
993,1025,2023-06-26,David,North,2457.65,47,Furniture,3861.61,3998.91,New,0.25,Credit Card,Online,North-David
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob

In [9]:
# Find all online sales
df[df["Sales_Channel"] == "Online"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,1025,2023-06-26,David,North,2457.65,47,Furniture,3861.61,3998.91,New,0.25,Credit Card,Online,North-David
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [10]:
# Find all retail sales.
df[df["Sales_Channel"] == "Retail"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
12,1024,2023-11-11,Eve,West,6607.80,21,Food,622.01,641.09,Returning,0.00,Bank Transfer,Retail,West-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,1025,2023-12-30,David,West,9215.32,28,Electronics,2097.84,2270.99,New,0.13,Credit Card,Retail,West-David
990,1017,2023-01-20,Bob,East,496.59,29,Clothing,3410.49,3481.72,New,0.24,Bank Transfer,Retail,East-Bob
991,1013,2023-06-01,Charlie,East,2985.46,16,Furniture,1222.15,1284.36,Returning,0.03,Credit Card,Retail,East-Charlie
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob

In [11]:
# Find customers with discounts greater than 10.

df[df["Discount"] > 10]

Empty DataFrame
Columns: [Product_ID, Sale_Date, Sales_Rep, Region, Sales_Amount, Quantity_Sold, Product_Category, Unit_Cost, Unit_Price, Customer_Type, Discount, Payment_Method, Sales_Channel, Region_and_Sales_Rep]
Index: []

In [12]:
# Find sales where:
# Sales_Amount > 5000
# AND
# Quantity_Sold > 5

df[(df["Sales_Amount"] > 5000) & (df["Quantity_Sold"] > 5)]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
12,1024,2023-11-11,Eve,West,6607.80,21,Food,622.01,641.09,Returning,0.00,Bank Transfer,Retail,West-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,1074,2023-12-16,Bob,North,6310.56,19,Furniture,278.67,423.13,New,0.24,Credit Card,Online,North-Bob
983,1039,2023-08-01,Eve,West,7527.63,36,Clothing,2919.00,3125.01,New,0.24,Cash,Online,West-Eve
989,1025,2023-12-30,David,West,9215.32,28,Electronics,2097.84,2270.99,New,0.13,Credit Card,Retail,West-David
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David

In [13]:
# Find sales made by a specific sales rep.
df[df["Sales_Rep"] == "Bob"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
11,1100,2023-08-14,Bob,West,2198.74,43,Food,1100.81,1137.44,Returning,0.08,Bank Transfer,Online,West-Bob
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,1056,2023-12-27,Bob,East,7979.67,4,Food,1612.82,1647.25,Returning,0.04,Credit Card,Retail,East-Bob
981,1028,2023-11-01,Bob,East,7946.69,24,Food,911.11,1214.56,New,0.22,Bank Transfer,Online,East-Bob
982,1074,2023-12-16,Bob,North,6310.56,19,Furniture,278.67,423.13,New,0.24,Credit Card,Online,North-Bob
990,1017,2023-01-20,Bob,East,496.59,29,Clothing,3410.49,3481.72,New,0.24,Bank Transfer,Retail,East-Bob
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob

In [14]:
# Find sales from the South region.
df[df["Region"] == "South"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
8,1075,2023-06-29,David,South,4223.39,30,Furniture,738.06,1095.45,New,0.05,Bank Transfer,Online,South-David
13,1003,2023-12-31,Alice,South,4775.59,30,Furniture,4190.28,4270.65,New,0.20,Cash,Online,South-Alice
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,1090,2023-10-15,Charlie,South,9702.27,48,Electronics,4766.53,5253.07,Returning,0.01,Bank Transfer,Online,South-Charlie
970,1059,2023-11-08,David,South,8466.70,17,Clothing,1780.14,2185.42,Returning,0.15,Credit Card,Retail,South-David
986,1086,2023-10-20,David,South,3577.07,32,Furniture,84.86,517.18,Returning,0.20,Credit Card,Retail,South-David
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David

In [15]:
# Find sales with discounts greater than 20%.
df[df["Discount"]  > 20 ]

Empty DataFrame
Columns: [Product_ID, Sale_Date, Sales_Rep, Region, Sales_Amount, Quantity_Sold, Product_Category, Unit_Cost, Unit_Price, Customer_Type, Discount, Payment_Method, Sales_Channel, Region_and_Sales_Rep]
Index: []

In [16]:
# Find sales paid using a specific payment method.
df[df["Payment_Method"] == "Bank Transfer"]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
8,1075,2023-06-29,David,South,4223.39,30,Furniture,738.06,1095.45,New,0.05,Bank Transfer,Online,South-David
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,1017,2023-01-20,Bob,East,496.59,29,Clothing,3410.49,3481.72,New,0.24,Bank Transfer,Retail,East-Bob
992,1084,2023-02-19,David,West,2154.66,35,Food,465.61,812.91,New,0.16,Bank Transfer,Online,West-David
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David

In [17]:
# Find products whose unit price is greater than 500.
df[df["Unit_Price"] > 500]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
5,1021,2023-02-11,Charlie,West,3761.15,32,Food,900.79,1106.51,New,0.21,Cash,Online,West-Charlie
6,1083,2023-04-11,Bob,West,618.31,29,Furniture,2408.81,2624.09,Returning,0.14,Cash,Online,West-Bob
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [18]:
# Find B2B customers.
df[df["Customer_Type"] == "B2B"]

Empty DataFrame
Columns: [Product_ID, Sale_Date, Sales_Rep, Region, Sales_Amount, Quantity_Sold, Product_Category, Unit_Cost, Unit_Price, Customer_Type, Discount, Payment_Method, Sales_Channel, Region_and_Sales_Rep]
Index: []

In [19]:
# Find B2C customers.
df[df["Customer_Type"] == "B2C"]

Empty DataFrame
Columns: [Product_ID, Sale_Date, Sales_Rep, Region, Sales_Amount, Quantity_Sold, Product_Category, Unit_Cost, Unit_Price, Customer_Type, Discount, Payment_Method, Sales_Channel, Region_and_Sales_Rep]
Index: []

In [20]:
# Find the top 10 highest sales amounts.
df.sort_values(by = "Sales_Amount" , ascending = False).head(10)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
755,1036,2023-12-10,David,North,9989.04,7,Food,2882.25,3163.70,Returning,0.05,Cash,Retail,North-David
760,1050,2023-08-21,David,North,9976.52,17,Furniture,2346.80,2654.65,New,0.13,Cash,Retail,North-David
855,1079,2023-08-24,Alice,North,9972.66,8,Clothing,3808.23,3891.62,Returning,0.26,Bank Transfer,Online,North-Alice
654,1075,2023-08-15,Charlie,North,9972.11,28,Clothing,2570.22,2610.84,Returning,0.27,Bank Transfer,Retail,North-Charlie
748,1016,2023-04-23,David,South,9961.96,6,Furniture,4502.09,4879.72,New,0.13,Credit Card,Online,South-David
796,1063,2023-08-14,Bob,North,9956.75,27,Clothing,3760.25,4147.11,New,0.22,Cash,Online,North-Bob
142,1099,2023-04-14,Alice,East,9948.71,27,Food,4929.55,4990.33,Returning,0.29,Credit Card,Online,East-Alice
189,1089,2023-10-19,Eve,West,9933.22,23,Food,2120.54,2597.67,Returning,0.26,Credit Card,Retail,West-Eve
89,1015,2023-09-22,David,South,9914.15,22,Electronics,4275.59,4576.72,Returning,0.02,Cash,Retail,South-David
784,1010,2023-10-12,Charlie,North,9907.72,20,Furniture,4298.74,4475.19,Returning,0.16,Cash,Online,North-Charlie

In [21]:
# Find the top 5 most expensive products (Unit_Price)
df.sort_values(by = "Unit_Price" , ascending = False).head(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
764,1100,2023-12-01,Alice,East,1387.80,34,Furniture,4991.09,5402.28,Returning,0.00,Cash,Retail,East-Alice
806,1001,2023-05-10,David,East,3793.91,47,Food,4865.33,5316.13,New,0.06,Bank Transfer,Online,East-David
807,1021,2023-06-24,Alice,West,9422.75,24,Electronics,4916.17,5309.32,Returning,0.19,Credit Card,Online,West-Alice
840,1026,2023-03-20,Bob,East,614.69,19,Electronics,4991.68,5296.65,New,0.12,Bank Transfer,Online,East-Bob

In [22]:
# Find products with the highest quantity sold.
df.sort_values(by = "Quantity_Sold" , ascending = False).head(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
282,1094,2023-03-04,Bob,North,3992.63,49,Food,615.47,715.84,Returning,0.21,Credit Card,Retail,North-Bob
276,1092,2023-03-25,Alice,West,1897.98,49,Furniture,2315.00,2467.28,New,0.15,Bank Transfer,Retail,West-Alice
425,1008,2023-12-08,Alice,South,3197.78,49,Electronics,2907.22,3385.61,New,0.13,Cash,Online,South-Alice
913,1067,2023-05-23,Bob,North,3133.99,49,Furniture,2628.38,2644.54,Returning,0.11,Cash,Online,North-Bob
144,1078,2023-02-08,Alice,South,9813.32,49,Furniture,3026.85,3183.58,Returning,0.25,Cash,Retail,South-Alice

In [23]:
# Find online sales with discounts greater than 15%.
df[(df['Sales_Channel'] == "Online") & (df["Discount"] > 15)]

Empty DataFrame
Columns: [Product_ID, Sale_Date, Sales_Rep, Region, Sales_Amount, Quantity_Sold, Product_Category, Unit_Cost, Unit_Price, Customer_Type, Discount, Payment_Method, Sales_Channel, Region_and_Sales_Rep]
Index: []

In [24]:
# Find sales from North region AND Online channel.
df[(df['Sales_Channel'] == "Online") & (df["Region"] == "North")]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
16,1002,2023-05-30,David,North,6810.35,17,Furniture,4024.76,4420.15,Returning,0.04,Cash,Online,North-David
20,1002,2023-04-22,Eve,North,6551.23,9,Electronics,4398.16,4439.12,New,0.18,Bank Transfer,Online,North-Eve
31,1059,2023-08-31,Alice,North,1203.97,35,Food,3333.64,3764.52,Returning,0.02,Credit Card,Online,North-Alice
32,1042,2023-01-31,Alice,North,5207.03,11,Food,635.20,814.14,Returning,0.02,Cash,Online,North-Alice
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,1017,2023-01-24,Eve,North,4637.40,27,Electronics,927.89,1399.09,Returning,0.27,Credit Card,Online,North-Eve
987,1090,2023-01-04,Eve,North,1028.39,14,Furniture,4037.21,4323.71,Returning,0.27,Credit Card,Online,North-Eve
988,1044,2023-08-08,Alice,North,4912.69,18,Clothing,430.14,641.18,New,0.13,Cash,Online,North-Alice
993,1025,2023-06-26,David,North,2457.65,47,Furniture,3861.61,3998.91,New,0.25,Credit Card,Online,North-David
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie

In [25]:
# Find products whose sales amount is above the average sales amount.
df[df["Sales_Amount"] > df["Sales_Amount"].mean()]

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
7,1087,2023-01-06,Eve,South,7698.92,46,Furniture,3702.51,3964.65,New,0.12,Bank Transfer,Online,South-Eve
9,1075,2023-10-09,Charlie,West,8239.58,18,Clothing,2228.35,2682.34,New,0.13,Bank Transfer,Online,West-Charlie
10,1088,2023-11-16,Eve,North,8518.45,13,Furniture,2440.11,2517.60,New,0.23,Bank Transfer,Retail,North-Eve
12,1024,2023-11-11,Eve,West,6607.80,21,Food,622.01,641.09,Returning,0.00,Bank Transfer,Retail,West-Eve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,1074,2023-12-16,Bob,North,6310.56,19,Furniture,278.67,423.13,New,0.24,Credit Card,Online,North-Bob
983,1039,2023-08-01,Eve,West,7527.63,36,Clothing,2919.00,3125.01,New,0.24,Cash,Online,West-Eve
989,1025,2023-12-30,David,West,9215.32,28,Electronics,2097.84,2270.99,New,0.13,Credit Card,Retail,West-David
994,1068,2023-04-06,Alice,South,9093.50,31,Clothing,3169.37,3304.15,Returning,0.25,Credit Card,Retail,South-Alice
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David