📅 Day 18 – Missing Values (Pandas)
Real-world datasets often contain missing values (NaN).

Today you'll learn how to:

✅ Detect missing values
✅ Remove missing values
✅ Fill missing values
✅ Replace missing values with mean values
📚 1. Create Dataset
import pandas as pd
import numpy as np

data = {
    "Name": ["A", "B", "C"],
    "Age": [20, np.nan, 22],
    "Salary": [50000, 60000, np.nan]
}

df = pd.DataFrame(data)

print(df)

Output:

  Name   Age   Salary
0    A  20.0  50000.0
1    B   NaN  60000.0
2    C  22.0      NaN
📚 2. Check Missing Values
Check every cell
df.isnull()

Output:

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
Count missing values
df.isnull().sum()

Output:

Name      0
Age       1
Salary    1
dtype: int64
📚 3. Remove Missing Values

Remove rows containing NaN.

df.dropna()

Output:

  Name   Age   Salary
0    A  20.0  50000.0
📚 4. Fill Missing Values

Replace all missing values with 0.

df.fillna(0)

Output:

  Name   Age   Salary
0    A  20.0  50000.0
1    B   0.0  60000.0
2    C  22.0      0.0
📚 5. Mean Replacement

Replace missing Age with average Age.

df["Age"] = df["Age"].fillna(df["Age"].mean())

print(df)

Output:

  Name   Age   Salary
0    A  20.0  50000.0
1    B  21.0  60000.0
2    C  22.0      NaN

Because:

(20 + 22) / 2 = 21

In [22]:
import pandas as pd
import numpy as np

data =  {"Name": ["A", "B", "C"],
    "Age": [20, np.nan, 22],
    "Salary": [50000, 60000, np.nan]
}

df = pd.DataFrame(data)
df

  Name   Age   Salary
0    A  20.0  50000.0
1    B   NaN  60000.0
2    C  22.0      NaN

In [3]:
df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

In [4]:
df.isnull().sum()

Name      0
Age       1
Salary    1
dtype: int64

In [6]:
#Remove Rows Containing NaN
df.dropna()

  Name   Age   Salary
0    A  20.0  50000.0

In [7]:
# Replace All missing Values with 0
df.fillna(0)

  Name   Age   Salary
0    A  20.0  50000.0
1    B   0.0  60000.0
2    C  22.0      0.0

In [10]:
# Replace missing Age with average Age.
df["Age"] = df["Age"].fillna(df['Age'].mean())
df

  Name   Age   Salary
0    A  20.0  50000.0
1    B  21.0  60000.0
2    C  22.0      NaN

In [11]:
# Count missing values in each column.
df.isnull().sum()

Name      0
Age       0
Salary    1
dtype: int64

In [12]:
# Find the total number of missing values in the dataset.
df.isnull().sum().sum()

np.int64(1)

In [13]:
# Display rows that contain at least one missing value.
df[df.isnull().any(axis = 1)]

  Name   Age  Salary
2    C  22.0     NaN

In [20]:
# Remove all rows that have missing values.
df.dropna()

  Name   Age   Salary
0    A  20.0  50000.0
1    B  21.0  60000.0

In [21]:
# Replace all missing values with 0.
df.fillna(0)

  Name   Age   Salary
0    A  20.0  50000.0
1    B  21.0  60000.0
2    C  22.0      0.0

In [24]:
# Replace missing values in Age with the average age.
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

  Name   Age   Salary
0    A  20.0  50000.0
1    B  21.0  60000.0
2    C  22.0      NaN

In [26]:
# Replace missing values in Salary with the average salary.
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

  Name   Age   Salary
0    A  20.0  50000.0
1    B  21.0  60000.0
2    C  22.0  55000.0

In [27]:
# Check if the dataset still contains any missing values.
df.isnull().sum().sum()

np.int64(0)

In [39]:
# Create a new dataset with 5 rows and at least 3 missing values, then:

# Count missing values
# Fill them with 0
# Fill them with mean values
# Remove rows with missing values

data = {"Name" : ["Dhruv" , "Riya" , "Aarush" , "Aman" , np.nan] , 
        "Salary" : [100000 , np.nan , 300000  , 400000 , 30000]  , 
        "Age" : [np.nan , 34 , 12, 45 ,19]}

df = pd.DataFrame(data)
print("Count missing values\n")
print(df.isnull().sum())

# print("\nFill them with 0")
# print(df.fillna(0))
print("Fill them with mean values")
df["Age"]  = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
print(df)
print("Remove rows with missing values")
df.dropna(inplace = True)
print(df)

Count missing values

Name      1
Salary    1
Age       1
dtype: int64
Fill them with mean values
     Name    Salary   Age
0   Dhruv  100000.0  27.5
1    Riya  207500.0  34.0
2  Aarush  300000.0  12.0
3    Aman  400000.0  45.0
4     NaN   30000.0  19.0
Remove rows with missing values
     Name    Salary   Age
0   Dhruv  100000.0  27.5
1    Riya  207500.0  34.0
2  Aarush  300000.0  12.0
3    Aman  400000.0  45.0

In [44]:
# Create this DataFrame:

# Name	Age	Salary
# Dhruv	21	50000
# Aman	NaN	60000
# Riya	23	NaN
# Neha	NaN	70000

# Perform:

# Count missing values
# Fill Age with mean
# Fill Salary with mean
# Verify no missing values remain

data = {"Name" : ["Dhruv" , "Aman" , "Riya" , "Neha" ] , 
        "Age" : [21 , np.nan , 23 , np.nan ] , 
        "Salary" : [50000 , 60000 , np.nan , 70000]}
df = pd.DataFrame(data)
print("Counting Missing Values") 
print(df.isnull().sum().sum())
print()
print("Filling Age with mean")
df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)
print("Filling Salary with mean")
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
print(df)
print()
print("Verify No missing Values remain")
print(df.isnull().sum())

Counting Missing Values
3

Filling Age with mean
    Name   Age   Salary
0  Dhruv  21.0  50000.0
1   Aman  22.0  60000.0
2   Riya  23.0      NaN
3   Neha  22.0  70000.0
Filling Salary with mean
    Name   Age   Salary
0  Dhruv  21.0  50000.0
1   Aman  22.0  60000.0
2   Riya  23.0  60000.0
3   Neha  22.0  70000.0

Verify No missing Values remain
Name      0
Age       0
Salary    0
dtype: int64