
#### Load the dataset into a DataFrame named df and display the first 5 rows.

In [14]:
import pandas as pd 

df = pd.read_csv("students.csv") 
df.head()

   StudentID   Name  Age  Gender  Marks    City AdmissionDate  Scholarship
0          1   Aman   20    Male     85   Delhi    2024-01-15         True
1          2   Riya   21  Female     92  Mumbai    2024-02-10        False
2          3  Rohit   19    Male     76    Pune    2024-03-05         True
3          4   Neha   22  Female     88   Delhi    2024-01-20        False
4          5  Karan   20    Male     90  Jaipur    2024-04-12         True

#### Write one line of code to display the last 5 rows of the dataset.

In [13]:
df.tail()

   StudentID    Name  Age  Gender  Marks    City AdmissionDate  Scholarship
5          6   Priya   21  Female     95  Mumbai    2024-05-18         True
6          7   Arjun   23    Male     80    Pune    2024-06-25        False
7          8   Sneha   20  Female     87   Delhi    2024-07-10         True
8          9   Vikas   22    Male     78  Jaipur    2024-08-01        False
9         10  Anjali   21  Female     91   Delhi    2024-09-15         True

#### Write one line of code to display the number of rows and columns in the dataset.

In [15]:
df.shape

(10, 8)

#### Write one line of code to display all column names in the dataset.

In [16]:
df.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'Marks', 'City', 'AdmissionDate',
       'Scholarship'],
      dtype='object')

#### Which columns are numerical?

In [9]:
df.columns

Index(['StudentID', 'Name', 'Age', 'Gender', 'Marks', 'City', 'AdmissionDate',
       'Scholarship'],
      dtype='object')

#### Write one line of code to display:

- data types
- non-null values
- memory usage
#### using a single Pandas function.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StudentID      10 non-null     int64
 1   Name           10 non-null     object
 2   Age            10 non-null     int64
 3   Gender         10 non-null     object
 4   Marks          10 non-null     int64
 5   City           10 non-null     object
 6   AdmissionDate  10 non-null     object
 7   Scholarship    10 non-null     bool
dtypes: bool(1), int64(3), object(4)
memory usage: 702.0+ bytes

#### Write one line of code to display the statistical summary of all numerical columns.?

In [18]:
df.describe()

       StudentID        Age      Marks
count   10.00000  10.000000  10.000000
mean     5.50000  20.900000  86.200000
std      3.02765   1.197219   6.356099
min      1.00000  19.000000  76.000000
25%      3.25000  20.000000  81.250000
50%      5.50000  21.000000  87.500000
75%      7.75000  21.750000  90.750000
max     10.00000  23.000000  95.000000

#### Write one line of code to display 5 random rows from the dataset.

In [20]:
df.sample(5)

   StudentID    Name  Age  Gender  Marks    City AdmissionDate  Scholarship
1          2    Riya   21  Female     92  Mumbai    2024-02-10        False
9         10  Anjali   21  Female     91   Delhi    2024-09-15         True
8          9   Vikas   22    Male     78  Jaipur    2024-08-01        False
6          7   Arjun   23    Male     80    Pune    2024-06-25        False
3          4    Neha   22  Female     88   Delhi    2024-01-20        False