In [8]:
import pandas as pd 

df = pd.read_csv("employee_data.csv") 
df.head()

,Employee_ID,Name,Department,Age,Salary,Date_Joined,Email,Phone,City,Performance_Score,Bonus
0,101,Amit,Sales,25,45000.0,15-01-2022,amit@gmail.com,9.876543e+09,Delhi,8.5,5000.0
1,102,Priya,HR,29,52000.0,20-03-2021,priya@gmail.com,9.876543e+09,Mumbai,9,6000.0
2,103,Rahul,IT,NaN,65000.0,15-06-2020,rahul@gmail.com,9.876543e+09,Bangalore,8.8,7000.0
3,104,Neha,Finance,31,58000.0,10-11-2020,neha@gmail.com,9.876543e+09,Pune,9.2,6500.0
4,105,Karan,IT,27,NaN,25-08-2019,karan@gmail.com,9.876543e+09,Delhi,8.1,5500.0

In [9]:
print("Number of Rows : " , df.shape[0] ) 
print("Number of Columns : " , df.shape[1] )

Number of Rows :  16
Number of Columns :  11

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        16 non-null     int64
 1   Name               16 non-null     object
 2   Department         16 non-null     object
 3   Age                15 non-null     object
 4   Salary             15 non-null     float64
 5   Date_Joined        15 non-null     object
 6   Email              15 non-null     object
 7   Phone              15 non-null     float64
 8   City               15 non-null     object
 9   Performance_Score  15 non-null     object
 10  Bonus              15 non-null     float64
dtypes: float64(3), int64(1), object(7)
memory usage: 1.5+ KB

In [11]:
df.isnull().sum()

Employee_ID          0
Name                 0
Department           0
Age                  1
Salary               1
Date_Joined          1
Email                1
Phone                1
City                 1
Performance_Score    1
Bonus                1
dtype: int64

#### Find the percentage of missing values in each column.

In [13]:
( df.isnull().sum() / len(df) ) * 100

Employee_ID          0.00
Name                 0.00
Department           0.00
Age                  6.25
Salary               6.25
Date_Joined          6.25
Email                6.25
Phone                6.25
City                 6.25
Performance_Score    6.25
Bonus                6.25
dtype: float64

#### Find the total number of duplicate rows in the dataset.

In [17]:
df.duplicated().sum()

np.int64(1)

#### Remove all duplicate rows from the original DataFrame.

In [20]:
df.drop_duplicates(inplace = True)

#### Display the names of all columns in the DataFrame.

In [21]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Salary', 'Date_Joined',
       'Email', 'Phone', 'City', 'Performance_Score', 'Bonus'],
      dtype='object')

#### Rename the column Date_Joined to Joining_Date.

In [22]:
df.rename( columns = { "Date_Joined" : "Joining_Date"} , inplace = True)

#### Convert the Joining_Date column to the datetime data type.

In [27]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"] , errors = "coerce")

#### Find all rows where Age is missing.

In [29]:
df[df["Age"].isnull()]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
2,103,Rahul,IT,NaN,65000.0,2020-06-15,rahul@gmail.com,9.876543e+09,Bangalore,8.8,7000.0

#### Find all rows where the Salary column has missing values.

In [30]:
df[df["Salary"].isnull()]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
4,105,Karan,IT,27,NaN,2019-08-25,karan@gmail.com,9.876543e+09,Delhi,8.1,5500.0

#### Find all rows where Age is not missing.

In [39]:
df[df["Age"].notnull()]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
0,101,Amit,Sales,25,45000.0,2022-01-15,amit@gmail.com,9.876543e+09,Delhi,8.5,5000.0
1,102,Priya,HR,29,52000.0,2021-03-20,priya@gmail.com,9.876543e+09,Mumbai,9,6000.0
3,104,Neha,Finance,31,58000.0,2020-11-10,neha@gmail.com,9.876543e+09,Pune,9.2,6500.0
4,105,Karan,IT,27,NaN,2019-08-25,karan@gmail.com,9.876543e+09,Delhi,8.1,5500.0
5,106,Anjali,Marketing,26,47000.0,2022-02-18,anjali@gmail.com,9.876543e+09,Jaipur,NaN,5000.0
6,107,Vikas,Sales,35,70000.0,2021-05-30,NaN,9.876543e+09,Delhi,9.4,8000.0
7,108,Simran,HR,28,51000.0,2020-09-15,simran@gmail.com,NaN,Mumbai,8.6,6000.0
8,109,Rohit,Finance,30,60000.0,2019-12-01,rohit@gmail.com,9.876543e+09,NaN,8.9,NaN
9,110,Sneha,IT,24,48000.0,2022-07-22,sneha@gmail.com,9.876543e+09,Bangalore,8.3,4500.0
11,111,Arjun,Sales,twenty six,55000.0,2021-10-05,arjun@gmail.com,9.876543e+09,Delhi,8,5200.0
12,112,Kavya,Marketing,29,54000.0,2020-03-12,kavya@gmail.com,9.876543e+09,Chennai,Excellent,5800.0
13,113,Manish,Finance,33,62000.0,NaT,manish@gmail.com,9.876543e+09,Pune,9.1,6400.0
14,114,Pooja,HR,27,50000.0,NaT,pooja@gmail.com,9.876543e+09,Mumbai,8.4,5900.0
15,115,Deepak,IT,29,66000.0,2020-06-18,deepak@gmail.com,9.876543e+09,Bangalore,8.7,7200.0

#### Find all rows where Age is greater than 30.

In [44]:
df[df["Age"] > 30]

#### Find all rows where Department is "IT".

In [46]:
df[df["Department"] == "IT"]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
2,103,Rahul,IT,NaN,65000.0,2020-06-15,rahul@gmail.com,9.876543e+09,Bangalore,8.8,7000.0
4,105,Karan,IT,27,NaN,2019-08-25,karan@gmail.com,9.876543e+09,Delhi,8.1,5500.0
9,110,Sneha,IT,24,48000.0,2022-07-22,sneha@gmail.com,9.876543e+09,Bangalore,8.3,4500.0
15,115,Deepak,IT,29,66000.0,2020-06-18,deepak@gmail.com,9.876543e+09,Bangalore,8.7,7200.0

#### Find all rows where Salary is greater than 60000 AND Department is "IT".

In [53]:
df[(df["Salary"] > 60000) & (df["Department"] == "IT")]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
2,103,Rahul,IT,NaN,65000.0,2020-06-15,rahul@gmail.com,9.876543e+09,Bangalore,8.8,7000.0
15,115,Deepak,IT,29,66000.0,2020-06-18,deepak@gmail.com,9.876543e+09,Bangalore,8.7,7200.0

#### Find all rows where Department is either "IT" or "HR".

In [54]:
df[(df["Department"] == "IT") | (df["Department"] == "HR")]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
1,102,Priya,HR,29,52000.0,2021-03-20,priya@gmail.com,9.876543e+09,Mumbai,9,6000.0
2,103,Rahul,IT,NaN,65000.0,2020-06-15,rahul@gmail.com,9.876543e+09,Bangalore,8.8,7000.0
4,105,Karan,IT,27,NaN,2019-08-25,karan@gmail.com,9.876543e+09,Delhi,8.1,5500.0
7,108,Simran,HR,28,51000.0,2020-09-15,simran@gmail.com,NaN,Mumbai,8.6,6000.0
9,110,Sneha,IT,24,48000.0,2022-07-22,sneha@gmail.com,9.876543e+09,Bangalore,8.3,4500.0
14,114,Pooja,HR,27,50000.0,NaT,pooja@gmail.com,9.876543e+09,Mumbai,8.4,5900.0
15,115,Deepak,IT,29,66000.0,2020-06-18,deepak@gmail.com,9.876543e+09,Bangalore,8.7,7200.0

#### Find all rows where Salary is missing OR Age is missing.

In [55]:
df[(df["Salary"].isnull()) | (df["Age"].isnull())]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
2,103,Rahul,IT,NaN,65000.0,2020-06-15,rahul@gmail.com,9.876543e+09,Bangalore,8.8,7000.0
4,105,Karan,IT,27,NaN,2019-08-25,karan@gmail.com,9.876543e+09,Delhi,8.1,5500.0

#### Find all rows where Age is not numeric.

In [57]:
df[pd.to_numeric(df["Age"] , errors = "coerce").isna()]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
2,103,Rahul,IT,NaN,65000.0,2020-06-15,rahul@gmail.com,9.876543e+09,Bangalore,8.8,7000.0
11,111,Arjun,Sales,twenty six,55000.0,2021-10-05,arjun@gmail.com,9.876543e+09,Delhi,8,5200.0

#### Find all rows where Joining_Date cannot be converted into a valid datetime.

In [58]:
df[pd.to_datetime(df["Joining_Date"] , errors = "coerce").isna()]

,Employee_ID,Name,Department,Age,Salary,Joining_Date,Email,Phone,City,Performance_Score,Bonus
13,113,Manish,Finance,33,62000.0,NaT,manish@gmail.com,9.876543e+09,Pune,9.1,6400.0
14,114,Pooja,HR,27,50000.0,NaT,pooja@gmail.com,9.876543e+09,Mumbai,8.4,5900.0