In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('hotel_bookings.csv')
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
df['total_guests'] = df['adults'] + df['children'] + df['babies']
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,2.0
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,3.0
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,2.0
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,2.0
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,2.0

In [5]:
df['stay_duration'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,stay_duration
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0,1
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0,1
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06,2.0,7
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07,3.0,7
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07,2.0,7
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07,2.0,7
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07,2.0,9

In [6]:
df['total_revenue'] = df['adr'] * df["stay_duration"]
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,stay_duration,total_revenue
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0,0,0.00
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Transient,0.00,0,0,Check-Out,2015-07-01,2.0,0,0.00
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0,1,75.00
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Transient,75.00,0,0,Check-Out,2015-07-02,1.0,1,75.00
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,Transient,98.00,0,1,Check-Out,2015-07-03,2.0,2,196.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,Transient,96.14,0,0,Check-Out,2017-09-06,2.0,7,672.98
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,0,Transient,225.43,0,2,Check-Out,2017-09-07,3.0,7,1578.01
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,0,Transient,157.71,0,4,Check-Out,2017-09-07,2.0,7,1103.97
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,Transient,104.40,0,0,Check-Out,2017-09-07,2.0,7,730.80
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,0,Transient,151.20,0,2,Check-Out,2017-09-07,2.0,9,1360.80

In [8]:
df['is_family'] = (df['children'] + df['babies']) > 0
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,stay_duration,total_revenue,is_family
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,2.0,0,0.00,False
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,2.0,0,0.00,False
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,1.0,1,75.00,False
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,1.0,1,75.00,False
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,2.0,2,196.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,Transient,96.14,0,0,Check-Out,2017-09-06,2.0,7,672.98,False
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,Transient,225.43,0,2,Check-Out,2017-09-07,3.0,7,1578.01,False
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,Transient,157.71,0,4,Check-Out,2017-09-07,2.0,7,1103.97,False
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,Transient,104.40,0,0,Check-Out,2017-09-07,2.0,7,730.80,False
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,Transient,151.20,0,2,Check-Out,2017-09-07,2.0,9,1360.80,False

In [13]:
df['revenue_per_guest'] = np.where(df['total_guests'] == 0 ,np.nan ,df['total_revenue'] / df['total_guests']) 
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,stay_duration,total_revenue,is_family,revenue_per_guest
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0.00,0,0,Check-Out,2015-07-01,2.0,0,0.00,False,0.000000
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0.00,0,0,Check-Out,2015-07-01,2.0,0,0.00,False,0.000000
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,75.00,0,0,Check-Out,2015-07-02,1.0,1,75.00,False,75.000000
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,75.00,0,0,Check-Out,2015-07-02,1.0,1,75.00,False,75.000000
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,98.00,0,1,Check-Out,2015-07-03,2.0,2,196.00,False,98.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,96.14,0,0,Check-Out,2017-09-06,2.0,7,672.98,False,336.490000
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,225.43,0,2,Check-Out,2017-09-07,3.0,7,1578.01,False,526.003333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,157.71,0,4,Check-Out,2017-09-07,2.0,7,1103.97,False,551.985000
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,104.40,0,0,Check-Out,2017-09-07,2.0,7,730.80,False,365.400000
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,151.20,0,2,Check-Out,2017-09-07,2.0,9,1360.80,False,680.400000

In [15]:
df['is_long_stay'] = np.where(df['stay_duration'] >= 7 , True , False)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,total_guests,stay_duration,total_revenue,is_family,revenue_per_guest,is_long_stay
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,0,Check-Out,2015-07-01,2.0,0,0.00,False,0.000000,False
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,0,Check-Out,2015-07-01,2.0,0,0.00,False,0.000000,False
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,0,Check-Out,2015-07-02,1.0,1,75.00,False,75.000000,False
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,0,Check-Out,2015-07-02,1.0,1,75.00,False,75.000000,False
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,1,Check-Out,2015-07-03,2.0,2,196.00,False,98.000000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,0,Check-Out,2017-09-06,2.0,7,672.98,False,336.490000,True
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,0,2,Check-Out,2017-09-07,3.0,7,1578.01,False,526.003333,True
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,0,4,Check-Out,2017-09-07,2.0,7,1103.97,False,551.985000,True
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,0,Check-Out,2017-09-07,2.0,7,730.80,False,365.400000,True
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,0,2,Check-Out,2017-09-07,2.0,9,1360.80,False,680.400000,True

In [18]:
df['lead_time_group'] = pd.cut(df['lead_time'] , labels = ['Short' , 'Medium' , 'Long' , 'Very Long'] ,bins =  [-1,30,90,180,df['lead_time'].max()])
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,total_guests,stay_duration,total_revenue,is_family,revenue_per_guest,is_long_stay,lead_time_group
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Check-Out,2015-07-01,2.0,0,0.00,False,0.000000,False,Very Long
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Check-Out,2015-07-01,2.0,0,0.00,False,0.000000,False,Very Long
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Check-Out,2015-07-02,1.0,1,75.00,False,75.000000,False,Short
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Check-Out,2015-07-02,1.0,1,75.00,False,75.000000,False,Short
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,1,Check-Out,2015-07-03,2.0,2,196.00,False,98.000000,False,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,Check-Out,2017-09-06,2.0,7,672.98,False,336.490000,True,Short
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,2,Check-Out,2017-09-07,3.0,7,1578.01,False,526.003333,True,Long
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,4,Check-Out,2017-09-07,2.0,7,1103.97,False,551.985000,True,Medium
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,Check-Out,2017-09-07,2.0,7,730.80,False,365.400000,True,Long
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,2,Check-Out,2017-09-07,2.0,9,1360.80,False,680.400000,True,Very Long

In [19]:
df['weekend_ratio'] = np.where(df['stay_duration'] == 0 ,np.nan,df['stays_in_weekend_nights'] / df['stay_duration'])

In [20]:
df['has_special_request'] = np.where(df['total_of_special_requests'] > 0 , True , False)

In [21]:
df['guest_type'] = pd.cut(df['total_guests'] , bins = [-1,1,2,4,df['total_guests'].max()] , labels = ["Solo" , "Couple" , 'Family' , 'Group'])

# OR
conditions = [df['total_guests'] == 1 , 
              df['total_guests'] == 2 , 
             df['total_guests'].between(3,4),
             df['total_guests'] >= 5]

choices = ["Solo" , "Couple" , "Family" , "Group"]
df['guest_type'] = np.select(conditions , choices , default = "Unknown")

In [22]:
df['high_revenue_booking'] = np.where(df['total_revenue'] > df['total_revenue'].mean() , True , False)

In [24]:
conditions = [df['arrival_date_month'].isin(["December" , "January" , "February"]),
             df['arrival_date_month'].isin(["March" , "April" , "May"]),
             df['arrival_date_month'].isin(["June" , "July" , "August"]),
             df['arrival_date_month'].isin(["September" , "October" , "November"])]
choices = ["Winter" , "Spring" , "Summer" , "Autumn"]
df["season"] = np.select(conditions , choices , default = "Unknown")

In [25]:
conditions = [(df["lead_time"] >= 180) & (df["is_repeated_guest"] == 0) , 
              (df["lead_time"] >= 180) & (df["is_repeated_guest"] == 1) ,]
choices = ['High Risk' , 'Loyal Planner']
df["booking_priority"] = np.select(conditions , choices , default = "Normal")

In [26]:
conditions = [(df["total_revenue"] >= 1000) & (df['total_guests'] >= 4) , 
              (df['total_revenue'] >= 500 )]
choices = ['Premium' , 'Standard']
df['booking_value'] = np.select(conditions , choices , default = 'Budget')

In [27]:
conditions = [df["is_canceled"] == 1,
             df['booking_changes'] > 2 , 
             df['is_repeated_guest'] == 1]
choices = ['Cancelled' , 'Modified' , 'Repeat']
df['booking_status'] = np.select(conditions , choices , default = "Confirmed")